// Generated by gencpp from file rosservice_examples/Person.msg
// DO NOT EDIT!


#ifndef ROSSERVICE_EXAMPLES_MESSAGE_PERSON_H
#define ROSSERVICE_EXAMPLES_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <rosservice_examples/PersonRequest.h>
#include <rosservice_examples/PersonResponse.h>


namespace rosservice_examples
{

struct Person
{

typedef PersonRequest Request;
typedef PersonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Person
} // namespace rosservice_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosservice_examples::Person > {
  static const char* value()
  {
    return "32cf62e277fd1435f7bfc80085d654cd";
  }

  static const char* value(const ::rosservice_examples::Person&) { return value(); }
};

template<>
struct DataType< ::rosservice_examples::Person > {
  static const char* value()
  {
    return "rosservice_examples/Person";
  }

  static const char* value(const ::rosservice_examples::Person&) { return value(); }
};


// service_traits::MD5Sum< ::rosservice_examples::PersonRequest> should match 
// service_traits::MD5Sum< ::rosservice_examples::Person > 
template<>
struct MD5Sum< ::rosservice_examples::PersonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosservice_examples::Person >::value();
  }
  static const char* value(const ::rosservice_examples::PersonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosservice_examples::PersonRequest> should match 
// service_traits::DataType< ::rosservice_examples::Person > 
template<>
struct DataType< ::rosservice_examples::PersonRequest>
{
  static const char* value()
  {
    return DataType< ::rosservice_examples::Person >::value();
  }
  static const char* value(const ::rosservice_examples::PersonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosservice_examples::PersonResponse> should match 
// service_traits::MD5Sum< ::rosservice_examples::Person > 
template<>
struct MD5Sum< ::rosservice_examples::PersonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosservice_examples::Person >::value();
  }
  static const char* value(const ::rosservice_examples::PersonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosservice_examples::PersonResponse> should match 
// service_traits::DataType< ::rosservice_examples::Person > 
template<>
struct DataType< ::rosservice_examples::PersonResponse>
{
  static const char* value()
  {
    return DataType< ::rosservice_examples::Person >::value();
  }
  static const char* value(const ::rosservice_examples::PersonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERVICE_EXAMPLES_MESSAGE_PERSON_H
