// Generated by gencpp from file rostopic_examples/Person.msg
// DO NOT EDIT!


#ifndef ROSTOPIC_EXAMPLES_MESSAGE_PERSON_H
#define ROSTOPIC_EXAMPLES_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rostopic_examples
{
template <class ContainerAllocator>
struct Person_
{
  typedef Person_<ContainerAllocator> Type;

  Person_()
    : name()
    , age(0)
    , sex()  {
    }
  Person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , sex(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sex_type;
  _sex_type sex;





  typedef boost::shared_ptr< ::rostopic_examples::Person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rostopic_examples::Person_<ContainerAllocator> const> ConstPtr;

}; // struct Person_

typedef ::rostopic_examples::Person_<std::allocator<void> > Person;

typedef boost::shared_ptr< ::rostopic_examples::Person > PersonPtr;
typedef boost::shared_ptr< ::rostopic_examples::Person const> PersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rostopic_examples::Person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rostopic_examples::Person_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rostopic_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rostopic_examples': ['/home/yao/ros_tutorials/src/rostopic_examples/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rostopic_examples::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rostopic_examples::Person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostopic_examples::Person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rostopic_examples::Person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostopic_examples::Person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rostopic_examples::Person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rostopic_examples::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "325fe16279a15ea654618c53abf5bb96";
  }

  static const char* value(const ::rostopic_examples::Person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x325fe16279a15ea6ULL;
  static const uint64_t static_value2 = 0x54618c53abf5bb96ULL;
};

template<class ContainerAllocator>
struct DataType< ::rostopic_examples::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rostopic_examples/Person";
  }

  static const char* value(const ::rostopic_examples::Person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rostopic_examples::Person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
uint8  age\n\
string sex\n\
\n\
";
  }

  static const char* value(const ::rostopic_examples::Person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rostopic_examples::Person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.sex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rostopic_examples::Person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rostopic_examples::Person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "sex: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSTOPIC_EXAMPLES_MESSAGE_PERSON_H
